#!/usr/bin/env bash
# One-time setup: creates a bare git repo on the o2switch server plus a
# post-receive hook that checks out the code into the Node app's folder and
# runs the full build (npm ci, prisma generate, prisma migrate deploy, nuxt
# build) automatically every time you push. Run this once per environment,
# after you've created the Node.js app in cPanel and filled in
# deploy/deploy.config (see deploy/README.md).
#
# Second independent site from this same codebase: pass a target name (e.g.
# `bash deploy/setup-remote.sh logicielbi`), matching deploy.sh's own target
# argument — reads deploy/deploy.logicielbi.config instead of the default.
set -euo pipefail

TARGET="${1:-}"
CONFIG_NAME="deploy.config"
if [ -n "$TARGET" ]; then
  CONFIG_NAME="deploy.$TARGET.config"
fi

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$DIR/$CONFIG_NAME"

if [ ! -f "$CONFIG_FILE" ]; then
  echo "Missing $CONFIG_FILE — copy deploy.config.example to $CONFIG_NAME and fill it in first." >&2
  exit 1
fi
# shellcheck disable=SC1090
source "$CONFIG_FILE"

: "${SSH_HOST:?$CONFIG_NAME: SSH_HOST is required}"
: "${SSH_USER:?$CONFIG_NAME: SSH_USER is required}"
: "${REMOTE_APP_PATH:?$CONFIG_NAME: REMOTE_APP_PATH is required}"
: "${REMOTE_NODE_ENV_ACTIVATE:?$CONFIG_NAME: REMOTE_NODE_ENV_ACTIVATE is required}"
SSH_PORT="${SSH_PORT:-22}"
REMOTE_GIT_DIR="${REMOTE_GIT_DIR:-git/caissebi.git}"

SSH="ssh -p $SSH_PORT $SSH_USER@$SSH_HOST"

echo "==> Creating bare repo ~/$REMOTE_GIT_DIR on $SSH_HOST"
$SSH "cd \$HOME && mkdir -p $REMOTE_GIT_DIR && git init --bare -q $REMOTE_GIT_DIR && mkdir -p '$REMOTE_APP_PATH'"

echo "==> Writing post-receive hook"
$SSH "cat > \$HOME/$REMOTE_GIT_DIR/hooks/post-receive" <<HOOK
#!/bin/bash
# Auto-generated by deploy/setup-remote.sh — safe to regenerate, don't hand-edit.
set -e
APP_DIR="$REMOTE_APP_PATH"

echo "==> Checking out latest code into \$APP_DIR"
GIT_WORK_TREE="\$APP_DIR" git checkout -f main

cd "\$APP_DIR"

echo "==> Activating Node environment"
source "$REMOTE_NODE_ENV_ACTIVATE"

echo "==> Installing dependencies"
npm ci

echo "==> Generating Prisma client (built for this server's platform)"
npx prisma generate

echo "==> Applying database migrations"
npx prisma migrate deploy

echo "==> Building the app"
npm run build

echo "==> Requesting restart"
mkdir -p tmp && touch tmp/restart.txt

echo "==> Deploy finished: \$(date)"
HOOK

$SSH "chmod +x \$HOME/$REMOTE_GIT_DIR/hooks/post-receive"

echo "==> Done."
echo ""
echo "Next: from the project root, run:"
if [ -n "$TARGET" ]; then
  echo "  bash deploy/deploy.sh $TARGET"
else
  echo "  bash deploy/deploy.sh"
fi
