-- AlterTable
ALTER TABLE `RolePermission` MODIFY `role` ENUM('OWNER', 'MANAGER', 'GERANT', 'CASHIER') NOT NULL;

-- AlterTable
ALTER TABLE `User` MODIFY `role` ENUM('OWNER', 'MANAGER', 'GERANT', 'CASHIER') NOT NULL DEFAULT 'CASHIER';
